### ISSUE TITLE
Possibility to shuffle element of array collection 

### ISSUE THREAD

**Issue by yassinechabli** [doctrine/collections#233]
type: feature
what about having a way to shuffle the element of arrayCollection 

```
public function shuffle($array){
    shuffle($this->element);
    return $this;
}
```

**Comment by SenseException** [comment]
Thanks for your suggestion. I don't think that such a feature should be implemented into Collections and belongs more into the logic of the project that is using it. Collections already have a high amount of methods and functionalities that need to be split up somehow instead of introducing new methods.

**Comment by greg0ire** [comment]
Thanks for your suggestion but I'm closing here, thanks for understanding.
