### ISSUE TITLE
Question: Usage of Comparable Interface

### ISSUE THREAD

**Issue by re2bit** [doctrine/collections#260]
Will https://github.com/doctrine/collections/blob/1.6.x/lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php use the https://github.com/doctrine/common/blob/3.1.x/lib/Doctrine/Common/Comparable.php Interface in future releases to overcome the Scalar Value Limitation ?

**Comment by greg0ire** [comment]
> the Scalar Value Limitation

Hi, what are you referring to?

`doctrine/collection` does not depend on `doctrine/common`, so whatever your answer, I'd say it is not very likely.

**Comment by re2bit** [comment]
As described in https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#filtering-collections

```
There is a limitation on the compatibility of Criteria comparisons. You have to use scalar values only as the value in a comparison or the behaviour between different backends is not the same.
```

Im tinkering around with a custom Value Object.
```
// won't work
$collectionInMemory->matching(Criteria:create()->wehre(Criteria::exp()->eq('email', $email)) 
// works since its translated to SQL (in case of ORM and Custom Type Mapping)
$lazyCollectionNotInitializedYet->matching(Criteria:create()->wehre(Criteria::exp()->eq('email', $email)) 
```

Currently comparing 2 Value Object with EQ/GT/LT... is not possible since the Objects are compared by Identity not Value.
On the other Hand CONTAINS, MEMBER_OF, ENDS_WITH work if the __toString Magic Method is implemented (at least so far I understood it) 

The "Problem" is the strict compare (which is needed to avoid problems with php resource ? I think I ocramius wrote somewhere something about that...)
```
class Money {
    public function __construct (
        private int $value = 0,
        private string $code = ''
        ) {}
}

$a = new Money(100, 'EUR');
$b = new Money(100, 'EUR');
$c = new Money(101, 'EUR');
var_dump($a == $b); // true
var_dump($a === $b); // false
var_dump($a == $c); // false
```

If the Collection is lazy and not initialized yet, a compare would still be possible since the ORM type mapping translates the Value Objects to corresponding scalar DB Values... at least when they are not stored as embeddables...

I thought it would be nice to delegate the actual comparison to the Object itself.
Something like.
```
$objectFieldValue = ClosureExpressionVisitor::getObjectFieldValue($object, $field);
if ($value instanceOf Compareable && $objectFieldValue instanceOf Compareable) {
  return $value->compareTo($objectFieldValue) === 0;
} else {
  objectFieldValue === $value;
}
```

Using a comparable Interface would not solve all Problems but in my opinion it would give folks like me, who like to play with custom value object types, a nice way to use the criteria API for Value Objects.

So my Question actually is: Is something planed for this Interface/"Problem" ? Maybe in Doctrine ORM 3 ?

**Comment by greg0ire** [comment]
> Maybe in Doctrine ORM 3 ?

I don't see what this has to do with the ORM, IMO this can be solved in this package. We could introduce a comparable interface in `doctrine/collection` and be done with it.

> You have to use scalar values only as the value in a comparison or the behaviour between different backends is not the same.

I don't really understand what "backends" means here, do you?

@beberlei you added this note in https://github.com/doctrine/orm/commit/9653213914db5742ef73951013df1c1f0a0059cb, maybe you can chime in? Did you maybe mean this piece of code will not work the same because the SQL would not be the same depending on which platform (as in MySQL, PostgreSQL, etc.) you use?

```php
// works since its translated to SQL (in case of ORM and Custom Type Mapping)
$lazyCollectionNotInitializedYet->matching(Criteria:create()->where(Criteria::exp()->eq('email', $email)) 
```

**Comment by beberlei** [comment]
In the original commit for `Comparable` you can see a `Doctrine\Common\DateTime\DateTime` we never used that in DBAL Types. Also handling of this interface was never committed to ORM UnitOfWork either. The case where we thought this might make sense is here:

https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/UnitOfWork.php#L719-L722

This is the ultra hot path of the UnitOfWork in case of flush, we always debated if the following would be an acceptable sacrifice:

```php
if ($actualValue instanceof Comparable && $actualValue->compareTo($orgValue) || $orgValue === $actualValue) {
```

Realistically, since you can't have the internal `DateTime(Interface)` implement comparable, you either need a Doctrine DateTime type or also make `$actualValue instanceof DateTimeInterface` another special case (hurting performance).

**Comment by beberlei** [comment]
This doesn't really answer the question, but the `Comparable` interface is probably best be deprecated and removed, because its not used anywhere. The problem space for Collections is interesting though, however its not as easy as importing the interface to collections and "be done", because without the types like DateTime implementing it, its not worthwhile.

A better approach would be to allow external configuration of comparables, i.e. ComparableRegistry::forValue($value)->compare($value, $other); However that would be an architectural decision if we want to add this kind of thing to Doctrine, not something that can be contributed externally sadly.

**Comment by ghost** [comment]
Thank you for your Answer.
I like the idea of moving the compare config out of the Object and keep it separate.

As I'm quite new to this whole OpenSource contribute socialize thing.... is there something left for me todo to push this Idea ?

I really would love to use the Criteria API regardless of InMemory or Database Backend for my Value Objects. And as far as I understood, is the comparison within the Closure Expression Visitor the only Thing that stops me from doing so. (At least without a Composer replace hack :) )
