### ISSUE TITLE
'Missing' reduce() functionality

### ISSUE THREAD

**Issue by holtkamp** [doctrine/collections#85]
While [reading about using collections to improve a code base](http://adamwathan.me/refactoring-to-collections/), I learned about the difference between a [ ```map()```](https://laravel.com/docs/5.1/collections#method-map) and a [```reduce()```](https://laravel.com/docs/5.1/collections#method-reduce) function. 

While this library currently has the ```map()``` function, it seems to 'miss' a ```reduce()``` function. This would be nice to, for example, calculate the total price of a collection of OrderLines.

Inspiration [here](https://github.com/laravel/framework/blob/5fa3e4e403209e8bfd987d406e3649034c259d05/src/Illuminate/Support/Collection.php#L693-L703). Would a PR be considered? Or is this library not intended to become bloated / complete? Just wondering 😄

**Comment by stof** [comment]
Adding a new method in the Collection interface cannot be considered until the next major version, as it would break backward compatibility (and this interface is meant to be implemented in other packages, for instance in many other Doctrine packages, so respecting semver is important)

**Comment by holtkamp** [comment]
Thanks for the swift reply, mmm, ok. And is a next major version already considered, the [milestones](https://github.com/doctrine/collections/milestones) don't mention it yet. Might be good to create one so we can collect more ideas?

**Comment by stof** [comment]
for now, there is no plan to make a new major version (the current interface fits the needs of the ORM and the different ODMs)

**Comment by holtkamp** [comment]
ok, closing issue then, will look for another approach, thanks!

**Comment by holtkamp** [comment]
Relevant approach might be to extend the used Collections class with additional functionality, also see: https://gist.github.com/jamesmoey/275faa6d58392fa742b6

**Comment by stof** [comment]
@holtkamp but in the context of the ORM, you cannot be sure that this extended implementation will always be used. When hydrating entities from the DB, the ORM uses its own implementation of the interface (the PersistentCollection) to be able to track changes in the collection and to lazy-load it (which is the reason why a collection object was introduced in the ORM btw)

**Comment by holtkamp** [comment]
Thanks for the heads-up @stof , also noticed https://github.com/doctrine/doctrine2/issues/5316.

**Comment by stof** [comment]
@holtkamp this would make the developer experience very bad, because they will think they can use these methods in their entity (they use an ArrayCollection in the constructor after all) and things will break totally when reloading the entity from the database.
For anything dealing with the ORM (or any ODMs as this is similar), you have no other choice than sticking to the interface (you may create a function ``iterator_reduce`` being able to reduce any iterator, and passing the collection, or just use https://github.com/nikic/iter or any other library already doing it).
If your usage of the collection has nothing to do with the ORM, my recommendation would be to switch to a different collection library aimed at providing what you need (there are many collection libraries on packagist).

**Comment by holtkamp** [comment]
@stof thanks for the patient explanation. We use the ORM Collections extensively, using an unobtrusive approach using https://github.com/nikic/iter is great advice!

**Comment by stephanvierkant** [comment]
Someone already did a Pull Request back in 2013: #16

Interesting blog post about using `array_reduce`: https://adamwathan.me/2016/07/14/customizing-keys-when-mapping-collections/
